services:
  frontend:
    build: ./frontend
    image: prescripto-frontend
    restart: always
    networks:
      - app-network

  admin:
    build: ./admin
    image: prescripto-admin
    restart: always
    networks:
      - app-network

  backend:
    build: ./backend
    image: prescripto-backend
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - app-network

  webserver:
    build: ./nginx
    image: prescripto-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - admin
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
