server {
    listen 80;

    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
    }

   location /admin/ {
        proxy_pass http://admin:80/;
    }

    location /api/ {

    if ($request_uri ~ ^/api/api/(.*)) {
        rewrite ^/api/api/(.*)$ /api/$1 break;
    }

    proxy_pass http://backend:3000;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
}
