name: Docter Appointment App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # ---------------- AWS CONFIG ----------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ================= BACKEND =================
      - name: Build & Push Backend
        run: |
          docker build -t canteen-backend ./Backend
          docker tag canteen-backend:latest ${{ secrets.ECR_BACKEND_URI }}:latest
          docker push ${{ secrets.ECR_BACKEND_URI }}:latest

      # ================= FRONTEND =================
      - name: Build & Push Frontend
        run: |
          docker build -t canteen-frontend ./Frontend
          docker tag canteen-frontend:latest ${{ secrets.ECR_FRONTEND_URI }}:latest
          docker push ${{ secrets.ECR_FRONTEND_URI }}:latest

      # ================= ADMIN =================
      - name: Build & Push Admin
        run: |
          docker build -t canteen-admin ./Admin
          docker tag canteen-admin:latest ${{ secrets.ECR_ADMIN_URI }}:latest
          docker push ${{ secrets.ECR_ADMIN_URI }}:latest

      # ================= DOWNLOAD TASK DEF =================
      - name: Download ECS task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ secrets.ECS_TASK_DEFINITION }} \
            --query taskDefinition \
            | jq 'del(
                .taskDefinitionArn,
                .revision,
                .status,
                .requiresAttributes,
                .compatibilities,
                .registeredAt,
                .registeredBy,
                .enableFaultInjection
              )' > task-definition.json

      # ================= RENDER UPDATED TASK DEF =================
      - name: Update Backend container
        id: backend-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ secrets.BACKEND_CONTAINER_NAME }}
          image: ${{ secrets.ECR_BACKEND_URI }}:latest

      - name: Update Frontend container
        id: frontend-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.backend-task.outputs.task-definition }}
          container-name: ${{ secrets.FRONTEND_CONTAINER_NAME }}
          image: ${{ secrets.ECR_FRONTEND_URI }}:latest

      - name: Update Admin container
        id: admin-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.frontend-task.outputs.task-definition }}
          container-name: ${{ secrets.ADMIN_CONTAINER_NAME }}
          image: ${{ secrets.ECR_ADMIN_URI }}:latest

      # ================= DEPLOY TO ECS =================
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.admin-task.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true
